print("Tipos de Dados no Python\n")
print("Numero inteiro")
print(1+10)
print("\nNumero com Ponto Flutuante")
print(1.5 + 1 + 0.5)
print("\nTipo Booleano")
print(True)
print(False)
print("\nTipo String")
print("Textos como por exemplo Python")